#将mdBook站点构建和部署到GitHub页面的示例工作流
#
#要开始使用MDbook，请参阅：https://rust-lang.github.io/mdBook/index.html
#
姓名：将mdBook站点部署到页面

在……之上:
  #在以默认分支为目标的推送上运行
推:
分支机构:["主要"]

  #允许您从“操作”选项卡手动运行此工作流
workflow_dispatch:

#设置GitHub_TOKEN的权限以允许部署到GitHub页面
权限:
内容:读
页面:写
id-token：写

#只允许一个并发部署，跳过正在运行和最新排队之间排队的运行。
#但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成。
并发性:
组:"页面"
正在取消:假的

工作:
  #生成作业
建立:
run-on:ubuntu-最新
env:
MDBOOK_VERSION:0.4.36
步骤:
-uses：操作/结帐@v4
-姓名：安装mdBook
跑:|
卷曲原型'=https'--tlsv1.2 https://sh.rustup.rs-sSf-y|sh
生锈更新
货物安装--版本${MDBOOK_VERSION}mdbook
-姓名:安装页面
身份标识:页面
使用：操作/configure-pages@v5
-姓名：使用mdBook构建
跑：mdbook构建
-姓名:上传工件
uses:action/upload-pages-artifact@v3
和……一起:
路径：./书

  #部署作业
部署:
环境:
姓名：github-pages
URL：${{steps.deployment.outputs.page_url}}
run-on:ubuntu-最新
需要:建立
步骤:
-姓名：部署到GitHub页面
身份标识:部署
操作/部署页面@v4
